CREATE MATERIALIZED VIEW vpview_all
AS
SELECT
  to_json(mappedtown) AS "mappedTown",
  to_json(visittown) AS "visitTown",
  vpmapped."mappedPoolId",
  vpmapped."mappedByUser",
  vpmapped."mappedByUserId",
  vpmapped."mappedDateText",
  vpmapped."mappedDateUnixSeconds",
  vpmapped."mappedLatitude",
  vpmapped."mappedLongitude",
  vpmapped."mappedConfidence",
  vpmapped."mappedSource",
  vpmapped."mappedSource2",
  vpmapped."mappedPhotoNumber",
  vpmapped."mappedLocationAccuracy",
  vpmapped."mappedShape",
  vpmapped."mappedComments",
  vpmapped."mappedlocationInfoDirections",
  vpmapped."mappedLandownerPermission",
  vpmapped."mappedLandownerInfo",
  vpmapped."mappedLocationUncertainty",
  vpmapped."mappedTownId",
  vpmapped."mappedPoolLocation",
  vpmapped."mappedPoolBorder",
  vpmapped."mappedLandownerName",
  vpmapped."mappedLandownerAddress",
  vpmapped."mappedLandownerTown",
  vpmapped."mappedLandownerStateAbbrev",
  vpmapped."mappedLandownerZip5",
  vpmapped."mappedLandownerPhone",
  vpmapped."mappedLandownerEmail",
  vpmapped."mappedPoolStatus",
  vpmapped."mappedMethod",
  vpmapped."mappedObserverUserName",
  vpmapped."updatedAt" AS "mappedUpdatedAt",
  vpmapped."createdAt" AS "mappedCreatedAt",
  vpmapped."mappedPoolId" AS "poolId",
  vpmapped."mappedLatitude" AS "latitude",
  vpmapped."mappedLongitude" AS "longitude",

  vpvisit."visitId",
  vpvisit."visitIdLegacy",
  vpvisit."visitUserName",
  vpvisit."visitPoolId",
  vpvisit."visitNavMethod",
  vpvisit."visitCertainty",
  vpvisit."visitLocatePool",
  vpvisit."visitDate",
  vpvisit."visitTownName",
  vpvisit."visitLocationComments",
  vpvisit."visitDirections",
  vpvisit."visitCoordSource",
  vpvisit."visitLatitude",
  vpvisit."visitLongitude",
  vpvisit."visitVernalPool",
  vpvisit."visitPoolType",
  vpvisit."visitInletType",
  vpvisit."visitOutletType",
  vpvisit."visitForestCondition",
  vpvisit."visitForestUpland",
  vpvisit."visitHabitatComment",
  vpvisit."visitHabitatAgriculture",
  vpvisit."visitHabitatLightDev",
  vpvisit."visitHabitatHeavyDev",
  vpvisit."visitHabitatPavedRd",
  vpvisit."visitHabitatDirtRd",
  vpvisit."visitHabitatPowerline",
  vpvisit."visitHabitatOther",
  vpvisit."visitMaxDepth",
  vpvisit."visitWaterLevelObs",
  vpvisit."visitHydroPeriod",
  vpvisit."visitMaxWidth",
  vpvisit."visitMaxLength",
  vpvisit."visitPoolTrees",
  vpvisit."visitPoolShrubs",
  vpvisit."visitPoolEmergents",
  vpvisit."visitPoolFloatingVeg",
  vpvisit."visitSubstrate",
  vpvisit."visitDisturbDumping",
  vpvisit."visitDisturbSiltation",
  vpvisit."visitDisturbVehicleRuts",
  vpvisit."visitDisturbRunoff",
  vpvisit."visitDisturbDitching",
  vpvisit."visitDisturbOther",
  vpvisit."visitWoodFrogAdults",
  vpvisit."visitWoodFrogLarvae",
  vpvisit."visitWoodFrogEgg",
  vpvisit."visitWoodFrogEggHow",
  vpvisit."visitSpsAdults",
  vpvisit."visitSpsLarvae",
  vpvisit."visitSpsEgg",
  vpvisit."visitSpsEggHow",
  vpvisit."visitJesaAdults",
  vpvisit."visitJesaLarvae",
  vpvisit."visitJesaEgg",
  vpvisit."visitJesaEggHow",
  vpvisit."visitBssaAdults",
  vpvisit."visitBssaLarvae",
  vpvisit."visitBssaEgg",
  vpvisit."visitBssaEggHow",
  vpvisit."visitFairyShrimp",
  vpvisit."visitFingerNailClams",
  vpvisit."visitSpeciesOther1",
  vpvisit."visitSpeciesOther2",
  vpvisit."visitSpeciesComments",
  vpvisit."visitFish",
  vpvisit."visitFishCount",
  vpvisit."visitFishSizeSmall",
  vpvisit."visitFishSizeMedium",
  vpvisit."visitFishSizeLarge",
  vpvisit."visitPoolPhoto",
  vpvisit."visitUserId",
  vpvisit."visitPoolMapped",
  vpvisit."visitUserIsLandowner",
  vpvisit."visitLandownerPermission",
  vpvisit."visitLandowner",
  vpvisit."visitTownId",
  vpvisit."visitFishSize",
  vpvisit."visitWoodFrogPhoto",
  vpvisit."visitWoodFrogNotes",
  vpvisit."visitSpsPhoto",
  vpvisit."visitSpsNotes",
  vpvisit."visitJesaPhoto",
  vpvisit."visitJesaNotes",
  vpvisit."visitBssaPhoto",
  vpvisit."visitBssaNotes",
  vpvisit."visitFairyShrimpPhoto",
  vpvisit."visitFairyShrimpNotes",
  vpvisit."visitFingerNailClamsPhoto",
  vpvisit."visitFingerNailClamsNotes",
  vpvisit."visitNavMethodOther",
  vpvisit."visitPoolTypeOther",
  vpvisit."visitSubstrateOther",
  vpvisit."visitSpeciesOtherName",
  vpvisit."visitSpeciesOtherCount",
  vpvisit."visitSpeciesOtherPhoto",
  vpvisit."visitSpeciesOtherNotes",
  vpvisit."visitLocationUncertainty",
  vpvisit."visitObserverUserName",
  vpvisit."visitWoodFrogiNat",
  vpvisit."visitSpsiNat",
  vpvisit."visitJesaiNat",
  vpvisit."visitBssaiNat",
  vpvisit."visitFairyShrimpiNat",
  vpvisit."visitFingerNailClamsiNat",
  vpvisit."visitSpeciesOtheriNat",
  vpvisit."updatedAt" AS "visitUpdatedAt",
  vpvisit."createdAt" AS "visitCreatedAt",

  vpreview."reviewId",
  vpreview."reviewUserName",
  vpreview."reviewUserId",
  vpreview."reviewPoolId",
  vpreview."reviewVisitIdLegacy",
  vpreview."reviewVisitId",
  vpreview."reviewQACode",
  vpreview."reviewQAAlt",
  vpreview."reviewQAPerson",
  vpreview."reviewQADate",
  vpreview."reviewQANotes",
  vpreview."reviewPoolStatus",
  vpreview."updatedAt" AS "reviewUpdatedAt",
  vpreview."createdAt" AS "reviewCreatedAt"

  FROM vpmapped
  LEFT JOIN vpvisit ON vpvisit."visitPoolId"=vpmapped."mappedPoolId"
  LEFT JOIN vptown AS mappedtown ON vpmapped."mappedTownId"=mappedtown."townId"
  LEFT JOIN vptown AS visittown ON vpvisit."visitTownId"=visittown."townId"
  LEFT JOIN vpreview ON vpreview."reviewVisitId"=vpvisit."visitId"
  WHERE
  (vpmapped."updatedAt">'1070-01-01'::timestamp
  OR vpvisit."updatedAt">'1970-01-01'::timestamp)

  ORDER BY "mappedPoolId"

WITH DATA;
